

service: web-scraper-lambda

plugins:
  - serverless-bundle
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
  resourceStages:
    prod: prod
    dev: dev


provider:
  name: aws
  runtime: nodejs12.x
  timeout: 5
  memorySize: 128
  stage: dev
functions:
  getSearches:
    handler: src/handler.getSearches
    events:
      - http:
          path: searches
          method: get
          cors: true

